<#
.SYNOPSIS
    Builds the master control registry (registry.json) from framework mappings and check-ID mappings.

.DESCRIPTION
    Reads two CSV sources and produces data/registry.json — the canonical registry
    mapping every CIS check to all its framework memberships including SOC 2.

    Source 1: data/framework-mappings.csv  (CIS controls + framework cross-references)
    Source 2: data/check-id-mapping.csv  (check IDs, collectors, areas)

    The script also derives SOC 2 Trust Services Criteria (CC) mappings from the
    NIST 800-53 control families present on each check.

.PARAMETER OutputPath
    Path to write the JSON registry. Defaults to data/registry.json relative to
    the repository root.

.NOTES
    Version:  1.0.0
    Author:   M365-Assess contributors

.EXAMPLE
    .\scripts\Build-Registry.ps1
    Generates data/registry.json from the default CSV sources.
#>
[CmdletBinding()]
param(
    [Parameter()]
    [string]$OutputPath
)

# Resolve repo root (parent of this script's directory)
$repoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)

if (-not $OutputPath) {
    $OutputPath = Join-Path $repoRoot 'data' 'registry.json'
}

$frameworkCsvPath    = Join-Path $repoRoot 'data' 'framework-mappings.csv'
$checkIdCsvPath      = Join-Path $repoRoot 'data' 'check-id-mapping.csv'
$standaloneJsonPath  = Join-Path $repoRoot 'data' 'standalone-checks.json'
$titleLookupPath     = Join-Path $repoRoot 'data' 'framework-titles.json'

# --- Load CSVs ---
$frameworkRows = Import-Csv -Path $frameworkCsvPath
$checkIdRows   = Import-Csv -Path $checkIdCsvPath

# --- Load framework title lookups (generated by Build-FrameworkTitles.py) ---
$frameworkTitles = @{}
if (Test-Path $titleLookupPath) {
    $titleData = Get-Content -Path $titleLookupPath -Raw | ConvertFrom-Json
    foreach ($fwKey in $titleData.PSObject.Properties.Name) {
        $lookup = @{}
        foreach ($prop in $titleData.$fwKey.PSObject.Properties) {
            $lookup[$prop.Name] = $prop.Value
        }
        $frameworkTitles[$fwKey] = $lookup
    }
    Write-Verbose "Loaded framework titles: $($frameworkTitles.Keys -join ', ')"
} else {
    Write-Warning "No framework-titles.json found — titles will not be added. Run Build-FrameworkTitles.py first."
}

# --- Load standalone checks (non-CIS automated checks with framework data) ---
$standaloneChecks = @()
if (Test-Path $standaloneJsonPath) {
    $standaloneChecks = Get-Content -Path $standaloneJsonPath -Raw | ConvertFrom-Json
}

# Index check-ID rows by CisControl
$checkIdMap = @{}
foreach ($row in $checkIdRows) {
    $checkIdMap[$row.CisControl] = $row
}

# --- SOC 2 mapping from NIST 800-53 control family prefixes ---
# Each key is a regex pattern matched against individual NIST control IDs.
# Order matters: more specific patterns are checked first.
$soc2MappingRules = [ordered]@{
    '^AC-2'      = 'CC6.1;CC6.2;CC6.3'
    '^AC-3'      = 'CC6.1;CC6.2;CC6.3'
    '^AC-4'      = 'CC6.1;CC6.7'
    '^AC-6'      = 'CC6.1;CC6.3'
    '^AC-11'     = 'CC6.1'
    '^AC-12'     = 'CC6.1'
    '^AC-17'     = 'CC6.1;CC6.7'
    '^AU-'       = 'CC7.1;CC7.2'
    '^IA-'       = 'CC6.1'
    '^CM-'       = 'CC5;CC8.1'
    '^SC-'       = 'CC6.1;CC6.7'
    '^SI-3'      = 'CC6.8;CC7.1'
    '^SI-8'      = 'CC6.8;CC7.1'
    '^SI-4'      = 'CC7.1;CC7.2'
    '^SI-'       = 'CC7.1'
}

function Get-Soc2CriteriaFromNist {
    [CmdletBinding()]
    param([string]$NistControlIds)

    if ([string]::IsNullOrWhiteSpace($NistControlIds)) { return $null }

    $allCriteria = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    $nistParts = $NistControlIds -split ';'

    foreach ($nistId in $nistParts) {
        $nistId = $nistId.Trim()
        if ([string]::IsNullOrWhiteSpace($nistId)) { continue }

        foreach ($pattern in $soc2MappingRules.Keys) {
            if ($nistId -match $pattern) {
                foreach ($cc in ($soc2MappingRules[$pattern] -split ';')) {
                    [void]$allCriteria.Add($cc.Trim())
                }
                break  # first matching rule wins for this NIST ID
            }
        }
    }

    if ($allCriteria.Count -eq 0) { return $null }

    # Sort criteria for consistent output
    $sorted = $allCriteria | Sort-Object {
        if ($_ -match 'CC(\d+)(?:\.(\d+))?') {
            [int]$Matches[1] * 100 + [int]($Matches[2] ?? 0)
        } else { 9999 }
    }
    return ($sorted -join ';')
}

function Resolve-FrameworkTitle {
    <#
    .SYNOPSIS
        Resolves a human-readable title for semicolon-separated control IDs.
    #>
    [CmdletBinding()]
    param(
        [string]$ControlIds,
        [string]$FrameworkKey
    )

    if ([string]::IsNullOrWhiteSpace($ControlIds)) { return $null }
    if (-not $frameworkTitles.ContainsKey($FrameworkKey)) { return $null }

    $lookup = $frameworkTitles[$FrameworkKey]
    $parts = $ControlIds -split ';'
    $resolved = [System.Collections.Generic.List[string]]::new()

    foreach ($cid in $parts) {
        $cid = $cid.Trim()
        if ([string]::IsNullOrWhiteSpace($cid)) { continue }

        $title = $null
        # Try exact match
        if ($lookup.ContainsKey($cid)) {
            $title = $lookup[$cid]
        }
        # Try uppercase
        elseif ($lookup.ContainsKey($cid.ToUpper())) {
            $title = $lookup[$cid.ToUpper()]
        }
        # For NIST-style IDs, try base without trailing lowercase letter
        else {
            $base = $cid -replace '[a-z]$', ''
            if ($lookup.ContainsKey($base)) {
                $title = $lookup[$base]
            } elseif ($lookup.ContainsKey($base.ToUpper())) {
                $title = $lookup[$base.ToUpper()]
            }
        }

        if ($title -and -not $resolved.Contains($title)) {
            $resolved.Add($title)
        }
    }

    if ($resolved.Count -eq 0) { return $null }
    return ($resolved -join '; ')
}

# --- Framework column to JSON key mapping ---
$frameworkColumnMap = [ordered]@{
    'NistCsf'   = 'nist-csf'
    'Nist80053'  = 'nist-800-53'
    'Iso27001'  = 'iso-27001'
    'Stig'      = 'stig'
    'PciDss'    = 'pci-dss'
    'Cmmc'      = 'cmmc'
    'Hipaa'     = 'hipaa'
    'CisaScuba' = 'cisa-scuba'
}

# --- CheckId prefix to collector name mapping ---
$collectorPrefixMap = @{
    'ENTRA'      = 'Entra'
    'EXO'        = 'ExchangeOnline'
    'SPO'        = 'SharePoint'
    'TEAMS'      = 'Teams'
    'DEFENDER'   = 'Defender'
    'COMPLIANCE' = 'Compliance'
    'INTUNE'     = 'Intune'
    'DNS'        = 'DNS'
    'CA'         = 'CAEvaluator'
}

# --- Build checks array ---
$checks = [System.Collections.Generic.List[object]]::new()

foreach ($fwRow in $frameworkRows) {
    $cisControl = $fwRow.CisControl
    $cidRow = $checkIdMap[$cisControl]

    if (-not $cidRow) {
        Write-Warning "No check-ID mapping found for CIS control $cisControl — skipping."
        continue
    }

    # Determine CIS profiles
    $profiles = [System.Collections.Generic.List[string]]::new()
    if (-not [string]::IsNullOrWhiteSpace($fwRow.CisE3L1)) { $profiles.Add('E3-L1') }
    if (-not [string]::IsNullOrWhiteSpace($fwRow.CisE3L2)) { $profiles.Add('E3-L2') }
    if (-not [string]::IsNullOrWhiteSpace($fwRow.CisE5L1)) { $profiles.Add('E5-L1') }
    if (-not [string]::IsNullOrWhiteSpace($fwRow.CisE5L2)) { $profiles.Add('E5-L2') }

    # Licensing: E5 only if no E3 profiles
    $hasE3 = (-not [string]::IsNullOrWhiteSpace($fwRow.CisE3L1)) -or
             (-not [string]::IsNullOrWhiteSpace($fwRow.CisE3L2))
    $minimumLicense = if ($hasE3) { 'E3' } else { 'E5' }

    # hasAutomatedCheck
    $checkId = $cidRow.CheckId
    $hasAutomated = -not ($checkId -like 'MANUAL-*')

    # Category and collector
    $category  = if ([string]::IsNullOrWhiteSpace($cidRow.Area)) { '' } else { $cidRow.Area }
    $collector = if ([string]::IsNullOrWhiteSpace($cidRow.Collector)) { '' } else { $cidRow.Collector }

    # SupersededBy
    $supersededBy = if ([string]::IsNullOrWhiteSpace($cidRow.SupersededBy)) { $null } else { $cidRow.SupersededBy.Trim() }

    # Build frameworks object — start with CIS
    $frameworks = [ordered]@{
        'cis-m365-v6' = [ordered]@{
            controlId = $cisControl
            title     = $fwRow.CisTitle
            profiles  = @($profiles)
        }
    }

    # Add other frameworks (with title lookup)
    foreach ($colName in $frameworkColumnMap.Keys) {
        $jsonKey = $frameworkColumnMap[$colName]
        $value = $fwRow.$colName
        if (-not [string]::IsNullOrWhiteSpace($value)) {
            $entry = [ordered]@{
                controlId = $value.Trim()
            }
            $title = Resolve-FrameworkTitle -ControlIds $value -FrameworkKey $jsonKey
            if ($title) {
                $entry['title'] = $title
            }
            $frameworks[$jsonKey] = $entry
        }
    }

    # Add SOC 2 derived from NIST 800-53
    $nist80053Value = $fwRow.Nist80053
    $soc2Criteria = Get-Soc2CriteriaFromNist -NistControlIds $nist80053Value
    if ($soc2Criteria) {
        $soc2Entry = [ordered]@{
            controlId    = $soc2Criteria
            evidenceType = 'config-export'
        }
        $soc2Title = Resolve-FrameworkTitle -ControlIds $soc2Criteria -FrameworkKey 'soc2'
        if ($soc2Title) {
            $soc2Entry['title'] = $soc2Title
        }
        $frameworks['soc2'] = $soc2Entry
    }

    $checkObj = [ordered]@{
        checkId           = $checkId
        name              = $fwRow.CisTitle
        category          = $category
        collector         = $collector
        hasAutomatedCheck = $hasAutomated
        licensing         = [ordered]@{ minimum = $minimumLicense }
        frameworks        = $frameworks
    }

    if ($supersededBy) {
        $checkObj['supersededBy'] = $supersededBy

        # Emit a second check entry for the automated superseder
        if ($supersededBy -match '^([A-Z]+)-(.+)-\d{3}$') {
            $ssCollectorPrefix = $Matches[1]
            $ssArea = $Matches[2]
            $ssCollector = if ($collectorPrefixMap.ContainsKey($ssCollectorPrefix)) {
                $collectorPrefixMap[$ssCollectorPrefix]
            } else { $ssCollectorPrefix }

            $ssCheckObj = [ordered]@{
                checkId           = $supersededBy
                name              = $fwRow.CisTitle
                category          = $ssArea
                collector         = $ssCollector
                hasAutomatedCheck = $true
                licensing         = [ordered]@{ minimum = $minimumLicense }
                frameworks        = $frameworks
            }
            $checks.Add($ssCheckObj)
        }
    }

    $checks.Add($checkObj)
}

# --- Emit standalone checks from standalone-checks.json ---
foreach ($sc in $standaloneChecks) {
    # Enrich standalone framework entries with titles
    $enrichedFrameworks = [ordered]@{}
    foreach ($fwProp in $sc.frameworks.PSObject.Properties) {
        $fwKey = $fwProp.Name
        $fwVal = $fwProp.Value
        $entry = [ordered]@{
            controlId = $fwVal.controlId
        }
        # Preserve existing fields
        foreach ($p in $fwVal.PSObject.Properties) {
            if ($p.Name -ne 'controlId') {
                $entry[$p.Name] = $p.Value
            }
        }
        # Add title if not already present and we have a lookup
        $hasTitle = $fwVal.PSObject.Properties.Name -contains 'title'
        if (-not $hasTitle) {
            $title = Resolve-FrameworkTitle -ControlIds $fwVal.controlId -FrameworkKey $fwKey
            if ($title) {
                $entry['title'] = $title
            }
        }
        $enrichedFrameworks[$fwKey] = $entry
    }
    $checkObj = [ordered]@{
        checkId           = $sc.checkId
        name              = $sc.name
        category          = $sc.category
        collector         = $sc.collector
        hasAutomatedCheck = $true
        licensing         = [ordered]@{ minimum = 'E3' }
        frameworks        = $enrichedFrameworks
    }
    $checks.Add($checkObj)
}

# Sort by CIS control ID (numerical sort on each dotted segment)
# Checks without CIS control sort to the end
$checks = $checks | Sort-Object {
    $fw = $_.frameworks
    $cis = if ($fw -is [System.Collections.IDictionary]) { $fw['cis-m365-v6'] }
           elseif ($fw.PSObject.Properties.Name -contains 'cis-m365-v6') { $fw.'cis-m365-v6' }
           else { $null }
    $cisId = if ($cis) { $cis.controlId } else { $null }
    if ([string]::IsNullOrWhiteSpace($cisId)) { return 'zzzz' }
    $parts = $cisId -split '\.'
    ($parts | ForEach-Object { $_.PadLeft(4, '0') }) -join '.'
}

# Build final registry object
$registry = [ordered]@{
    schemaVersion = '1.0.0'
    dataVersion   = (Get-Date -Format 'yyyy-MM-dd')
    generatedFrom = 'data/framework-mappings.csv + data/check-id-mapping.csv + data/standalone-checks.json'
    checks        = @($checks)
}

# Write JSON (UTF-8 no BOM)
$jsonText = $registry | ConvertTo-Json -Depth 10
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($OutputPath, $jsonText, $utf8NoBom)

Write-Host "Registry written to: $OutputPath"
Write-Host "Total checks:     $($checks.Count)"
Write-Host "Automated checks: $(($checks | Where-Object { $_.hasAutomatedCheck }).Count)"
Write-Host "Manual checks:    $(($checks | Where-Object { -not $_.hasAutomatedCheck }).Count)"
Write-Host "SOC 2 mappings:   $(($checks | Where-Object {
    ($_.frameworks -is [System.Collections.IDictionary] -and $_.frameworks.Contains('soc2')) -or
    ($_.frameworks -isnot [System.Collections.IDictionary] -and $_.frameworks.PSObject.Properties.Name -contains 'soc2')
}).Count)"
